import { Raleway, Aboreto } from "next/font/google";
import "./globals.css";

const mainFont = Raleway({
  display: "swap",
  subsets: ["latin"],
});

export const secondFont = Aboreto({
  display: "swap",
  subsets: ["latin"],
  weight: ['400'],
});

export const metadata = {
  title: "Golobe - Travel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.className} antialiased`}
      >
        <div>

        </div>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
